# Generated by Django 3.2 on 2021-05-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AskIndex',
            new_name='QuerySection',
        ),
    ]
