# Generated by Django 3.2 on 2021-05-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_askindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askindex',
            old_name='Firstname',
            new_name='FirstName',
        ),
    ]
