# Generated by Django 3.2 on 2021-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_askindex_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askindex',
            name='phone',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
