# Generated by Django 3.2 on 2021-05-01 11:58

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_askindex_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askindex',
            name='phone',
        ),
        migrations.AddField(
            model_name='askindex',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
