# Generated by Django 3.2 on 2021-05-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210529_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderTiming',
        ),
    ]
