# Generated by Django 3.2 on 2021-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210501_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askindex',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
