# Generated by Django 3.2 on 2021-05-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_phone_number_askindex_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askindex',
            old_name='phone',
            new_name='phone_field',
        ),
    ]
