# Generated by Django 3.2 on 2021-05-29 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_order_ordertiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 17, 30, 4, 592243, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
