# Generated by Django 3.2 on 2021-05-01 12:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_phone_askindex_phone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askindex',
            name='phone_field',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
