# Generated by Django 3.2 on 2021-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
