# Generated by Django 3.2 on 2021-05-15 12:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210501_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askindex',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default=0, max_length=31),
            preserve_default=False,
        ),
    ]
