# Generated by Django 3.2 on 2021-05-15 12:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_askindex_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askindex',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
