# Generated by Django 3.2 on 2021-05-15 12:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_askindex_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askindex',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
